In [39]:
# Importing necessary libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, Binarizer
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.metrics import confusion_matrix, accuracy_score, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report


In [40]:
# Loading data
data = pd.read_csv('game_details_with_counts.csv')


In [41]:
# Creating the 'cult_classic' feature
# Cult classic: high ratings (> 8) and high number of ratings (> 1000)
data['cult_classic'] = ((data['users_rated'] > 1000) & 
                        (data['average_rating'] > 8.0)).astype(int)

# Creating the 'game_night_game' feature
# Game night game: more than 4 players and high ratings (> 7)
data['game_night_game'] = ((data['max_players'] >= 4) & (data['average_rating'] > 7)).astype(int)

# Creating the 'high_complexity_game' feature
# High complexity game: high weight (> 3.5), long playtime (> 60 mins), more than 4 categories, and more than 4 mechanics
data['high_complexity_game'] = ((data['weight'] > 3.5) & 
                                 (data['max_playtime'] > 60) & 
                                 (data['category_count'] > 4) &
                                 (data['mechanic_count'] > 4)).astype(int)



In [42]:
print(data.columns)

Index(['name', 'year_published', 'min_players', 'max_players', 'min_playtime',
       'max_playtime', 'min_age', 'categories', 'mechanics', 'users_rated',
       'average_rating', 'weight', 'category_count', 'mechanic_count',
       'cult_classic', 'game_night_game', 'high_complexity_game'],
      dtype='object')


In [49]:
# Multinomial Naïve Bayes - Target: high_complexity_game
# Features: category_count, mechanic_count, min_players, max_players, min_playtime, max_playtime
multinomial_features = data[['weight', 'category_count', 'mechanic_count', 'min_players', 'max_players', 'min_playtime', 'max_playtime']].values
X_train_m, X_test_m, y_train_m, y_test_m = train_test_split(
    multinomial_features, data['high_complexity_game'], test_size=0.3, random_state=42
)


In [54]:
# Gaussian Naïve Bayes - Target: cult_classic
# Features: year_published, weight, users_rated, max_playtime, category_count
gaussian_features = data[['weight', 'category_count', 'mechanic_count', 'min_players', 'max_players', 'min_playtime', 'max_playtime', 'users_rated', 'average_rating']].values
scaler = StandardScaler()
gaussian_features_scaled = scaler.fit_transform(gaussian_features)

# Splitting dataset for Gaussian Naïve Bayes
X_train_g, X_test_g, y_train_g, y_test_g = train_test_split(
    gaussian_features_scaled, data['cult_classic'], test_size=0.3, random_state=42
)

In [51]:
# Bernoulli Naïve Bayes - Target: game_night_game
# Features: max_players and average_rating
bernoulli_features = data[['weight', 'category_count', 'mechanic_count', 'min_players', 'max_players', 'min_playtime', 'max_playtime']].values
X_train_b, X_test_b, y_train_b, y_test_b = train_test_split(
    bernoulli_features, data['high_complexity_game'], test_size=0.3, random_state=42
)

In [50]:
# Multinomial Naïve Bayes
mnb = MultinomialNB()
mnb.fit(X_train_m, y_train_m)
y_pred_m = mnb.predict(X_test_m)
print("Multinomial Naïve Bayes Results (High Complexity Game):")
print("Confusion Matrix:\n", confusion_matrix(y_test_m, y_pred_m))
print("Accuracy:", accuracy_score(y_test_m, y_pred_m))
print("Classification Report:\n", classification_report(y_test_m, y_pred_m))


Multinomial Naïve Bayes Results (High Complexity Game):
Confusion Matrix:
 [[801  68]
 [ 18  13]]
Accuracy: 0.9044444444444445
Classification Report:
               precision    recall  f1-score   support

           0       0.98      0.92      0.95       869
           1       0.16      0.42      0.23        31

    accuracy                           0.90       900
   macro avg       0.57      0.67      0.59       900
weighted avg       0.95      0.90      0.92       900



In [55]:
# Gaussian Naïve Bayes
gnb = GaussianNB()
gnb.fit(X_train_g, y_train_g)
y_pred_g = gnb.predict(X_test_g)
print("\nGaussian Naïve Bayes Results (Cult Classic):")
print("Confusion Matrix:\n", confusion_matrix(y_test_g, y_pred_g))
print("Accuracy:", accuracy_score(y_test_g, y_pred_g))
print("Classification Report:\n", classification_report(y_test_g, y_pred_g))



Gaussian Naïve Bayes Results (Cult Classic):
Confusion Matrix:
 [[748  51]
 [ 31  70]]
Accuracy: 0.9088888888888889
Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.94      0.95       799
           1       0.58      0.69      0.63       101

    accuracy                           0.91       900
   macro avg       0.77      0.81      0.79       900
weighted avg       0.92      0.91      0.91       900



In [53]:
# Bernoulli Naïve Bayes
bnb = BernoulliNB()
bnb.fit(X_train_b, y_train_b)
y_pred_b = bnb.predict(X_test_b)
print("\nBernoulli Naïve Bayes Results (High Complexity Game):")
print("Confusion Matrix:\n", confusion_matrix(y_test_b, y_pred_b))
print("Accuracy:", accuracy_score(y_test_b, y_pred_b))
print("Classification Report:\n", classification_report(y_test_b, y_pred_b))



Bernoulli Naïve Bayes Results (High Complexity Game):
Confusion Matrix:
 [[869   0]
 [ 31   0]]
Accuracy: 0.9655555555555555
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98       869
           1       0.00      0.00      0.00        31

    accuracy                           0.97       900
   macro avg       0.48      0.50      0.49       900
weighted avg       0.93      0.97      0.95       900



C:\Users\kenzi\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kenzi\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\kenzi\AppData\Roaming\Python\Python312\site-packages\sklearn\metrics\_classification.py:1497: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i